### ISSUE TITLE
Amazing tool, could need help with customising

### ISSUE THREAD

**Issue by VonZubinski** [putunebandi/searchsan#1]
Hi @putunebandi ,

thanks for this amazing tool. Since I'm not very familiar with python, is there a simple way to remove the comparison and use it to just print the whole json (organic, knowledge graph, suggestions...) ?

**Comment by VonZubinski** [comment]
Okay, figured out the problem myself and why no json data was printed. 
If you call the API with same query a 2nd time, there is no response.

**Comment by putunebandi** [comment]
> Okay, figured out the problem myself and why no json data was printed. If you call the API with same query a 2nd time, there is no response.

@VonZubinski Apologies for the delayed response. Please understand. The results of your search have been saved in the "data/query_searched.txt" file. If you wish to search again, you can delete it. Your complaints or suggestions will be noted as input for future feature improvements. Thank you for your feedback.
